github:
  username: lecy 
  reponame: nonprofitdataproject 

###
### NAVIGATION BAR
###

navbar:
- title: The Survey
  url: survey
- title: Survey Data Access
  url: data
- title: NCCS Catalog
  url: nccs
- title: Publications
  url: pubs
- title: The Platform
  url: platform
- title: About
  url: about

