github:
  username: lecy 
  reponame: nonprofitdataproject 

###
### NAVIGATION BAR
###

navbar:
- title: Home
  url: index
- title: Data
  url: data
- title: Sampling Framework
  url: sample
- title: Survey Instrument
  url: survey
- title: About
  url: about

