github:
  username: lecy 
  reponame: nonprofitdataproject 

###
### NAVIGATION BAR
###

navbar:
- title: The Surveys
  url: survey
- title: Survey Data Access
  url: data

- title: Publications
  url: pubs
- title: The Platform
  url: platform
- title: NCCS Catalog
  url: nccs
- title: About
  url: about
  
  
  

# jekyll scholar plugin
# https://gist.github.com/roachhd/ed8da4786ba79dfc4d91
# 
# plugins: ['jekyll/scholar']
# 
# whitelist: ['jekyll/scholar']

